name: wastewater
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - gdal=3.6.2
  - fiona=1.9.5
  - shapely=2.0.1
  - geopandas=0.13.2
  - pandas=1.5.3
  - numpy=1.24.3
  - matplotlib=3.7.1
  - xarray=2023.01.0
  - hdf5=1.12.1
  - cartopy
  - regionmask
  - seaborn
  - xesmf
  - rasterio
  - esmpy
  - pyogrio
  - pip
  - pip:
      - ipykernel
      - datetime
# name: wastewater
# channels:
#   - conda-forge
#   - defaults
# dependencies:
#   - _libgcc_mutex=0.1
#   - _openmp_mutex=4.5
#   - attrs=25.3.0
#   - blosc=1.21.5
#   - boost-cpp=1.85.0
#   - branca=0.8.1
#   - brotli=1.1.0
#   - brotli-bin=1.1.0
#   - brotli-python=1.1.0
#   - bzip2=1.0.8
#   - c-ares=1.34.5
#   - ca-certificates=2025.7.14
#   - cairo=1.16.0
#   - certifi=2025.7.14
#   - cffi=1.17.1
#   - cfitsio=3.470
#   - charset-normalizer=3.4.2
#   - click=8.1.8
#   - click-plugins=1.1.1.2
#   - cligj=0.7.2
#   - contourpy=1.3.0
#   - cycler=0.12.1
#   - cyrus-sasl=2.1.28
#   - expat=2.7.1
#   - fiona=1.9.5
#   - folium=0.20.0
#   - fontconfig=2.14.1
#   - fonttools=4.59.0
#   - freetype=2.13.3
#   - freexl=2.0.0
#   - gdal=3.6.2
#   - geopandas=0.13.2
#   - geopandas-base=0.13.2
#   - geos=3.8.0
#   - geotiff=1.7.0
#   - giflib=5.2.2
#   - h2=4.2.0
#   - hdf4=4.2.13
#   - hdf5=1.12.1
#   - hpack=4.1.0
#   - hyperframe=6.1.0
#   - icu=73.2
#   - idna=3.10
#   - importlib-metadata=8.7.0
#   - importlib-resources=6.5.2
#   - importlib_resources=6.5.2
#   - jinja2=3.1.6
#   - joblib=1.5.1
#   - jpeg=9e
#   - json-c=0.16
#   - kealib=1.5.0
#   - keyutils=1.6.1
#   - kiwisolver=1.4.7
#   - krb5=1.21.3
#   - lcms2=2.16
#   - ld_impl_linux-64=2.44
#   - lerc=3.0
#   - libabseil=20250127.0
#   - libblas=3.9.0
#   - libboost=1.85.0
#   - libboost-devel=1.85.0
#   - libboost-headers=1.85.0
#   - libbrotlicommon=1.1.0
#   - libbrotlidec=1.1.0
#   - libbrotlienc=1.1.0
#   - libcblas=3.9.0
#   - libcups=2.3.3
#   - libcurl=8.8.0
#   - libdeflate=1.17
#   - libdrm=2.4.125
#   - libedit=3.1.20250104
#   - libegl=1.7.0
#   - libev=4.33
#   - libexpat=2.7.1
#   - libffi=3.4.6
#   - libgcc=15.1.0
#   - libgcc-ng=15.1.0
#   - libgdal=3.6.2
#   - libgfortran=15.1.0
#   - libgfortran-ng=15.1.0
#   - libgfortran5=15.1.0
#   - libgl=1.7.0
#   - libglib=2.84.2
#   - libglvnd=1.7.0
#   - libglx=1.7.0
#   - libgomp=15.1.0
#   - libiconv=1.18
#   - libkml=1.3.0
#   - liblapack=3.9.0
#   - libllvm15=15.0.7
#   - liblzma=5.8.1
#   - liblzma-devel=5.8.1
#   - libnetcdf=4.8.1
#   - libnghttp2=1.58.0
#   - libnsl=2.0.1
#   - libntlm=1.8
#   - libopenblas=0.3.30
#   - libpciaccess=0.18
#   - libpng=1.6.43
#   - libpq=17.4
#   - libprotobuf=5.29.3
#   - libspatialindex=2.1.0
#   - libspatialite=5.1.0
#   - libsqlite=3.46.0
#   - libssh2=1.11.0
#   - libstdcxx=15.1.0
#   - libstdcxx-ng=15.1.0
#   - libtiff=4.5.1
#   - libuuid=1.41.5
#   - libwebp-base=1.6.0
#   - libxcb=1.17.0
#   - libxcrypt=4.4.36
#   - libxkbcommon=1.10.0
#   - libxml2=2.13.8
#   - libzip=1.10.1
#   - libzlib=1.2.13
#   - lz4-c=1.9.4
#   - mapclassify=2.8.1
#   - markupsafe=3.0.2
#   - matplotlib=3.7.1
#   - matplotlib-base=3.7.1
#   - mesalib=25.1.5
#   - minizip=4.0.6
#   - munkres=1.1.4
#   - mysql=8.4.0
#   - ncurses=6.5
#   - networkx=3.2.1
#   - nspr=4.37
#   - nss=3.100
#   - openjpeg=2.5.0
#   - openldap=2.6.10
#   - openssl>=1.1
#   - packaging=25.0
#   - pandas=1.5.3
#   - pcre2=10.42
#   - pillow=11.1.0
#   - pip=25.1.1
#   - pixman=0.46.4
#   - ply=3.11
#   - poppler=24.09.0
#   - poppler-data=0.4.12
#   - proj=9.3.1
#   - pthread-stubs=0.4
#   - pycparser=2.22
#   - pyparsing=3.2.3
#   - pyproj=3.6.1
#   - pyqt=6.7.1
#   - pyqt6-sip=13.9.1
#   - pysocks=1.7.1
#   - python>=3.10,<3.11
#   - python-dateutil=2.9.0.post0
#   - python_abi=3.9
#   - pytz=2025.2
#   - qhull=2020.2
#   - qtbase=6.7.3
#   - qtdeclarative=6.7.3
#   - qtsvg=6.7.3
#   - qttools=6.7.3
#   - qtwebchannel=6.7.3
#   - qtwebsockets=6.7.3
#   - readline=8.2
#   - requests=2.32.4
#   - rtree=1.4.0
#   - scikit-learn=1.6.1
#   - scipy=1.13.1
#   - setuptools=80.9.0
#   - shapely=2.0.1
#   - sip=6.10.0
#   - six=1.17.0
#   - snappy=1.2.2
#   - spirv-tools=2025.1
#   - sqlite=3.50.2
#   - threadpoolctl=3.6.0
#   - tiledb=2.3.3
#   - tk=8.6.13
#   - tomli=2.2.1
#   - tornado=6.5.1
#   - tzdata=2025b
#   - unicodedata2=16.0.0
#   - uriparser=0.9.8
#   - urllib3=2.5.0
#   - wheel=0.45.1
#   - xarray=2023.1.0
#   - xcb-util=0.4.1
#   - xcb-util-cursor=0.1.5
#   - xcb-util-image=0.4.0
#   - xcb-util-keysyms=0.4.1
#   - xcb-util-renderutil=0.3.10
#   - xcb-util-wm=0.4.2
#   - xerces-c=3.2.5
#   - xkeyboard-config=2.45
#   - xorg-libice=1.1.2
#   - xorg-libsm=1.2.6
#   - xorg-libx11=1.8.12
#   - xorg-libxau=1.0.12
#   - xorg-libxdmcp=1.1.5
#   - xorg-libxext=1.3.6
#   - xorg-libxfixes=6.0.1
#   - xorg-libxrandr=1.5.4
#   - xorg-libxrender=0.9.12
#   - xorg-libxshmfence=1.3.3
#   - xorg-libxxf86vm=1.1.6
#   - xorg-xorgproto=2024.1
#   - xyzservices=2025.4.0
#   - xz=5.8.1
#   - xz-gpl-tools=5.8.1
#   - xz-tools=5.8.1
#   - zipp=3.23.0
#   - zlib=1.2.13
#   - zstandard=0.23.0
#   - zstd=1.5.6
#   - pip:
#       - asttokens==3.0.0
#       - comm==0.2.2
#       - datetime==5.5
#       - debugpy==1.8.15
#       - decorator==5.2.1
#       - exceptiongroup==1.3.0
#       - executing==2.2.0
#       - ipykernel==6.30.0
#       - ipython==8.18.1
#       - jedi==0.19.2
#       - jupyter-client==8.6.3
#       - jupyter-core==5.8.1
#       - matplotlib-inline==0.1.7
#       - nest-asyncio==1.6.0
#       - numpy==2.0.2
#       - opencv-python==4.12.0.88
#       - parso==0.8.4
#       - patsy==1.0.1
#       - pexpect==4.9.0
#       - platformdirs==4.3.8
#       - prompt-toolkit==3.0.51
#       - psutil==7.0.0
#       - ptyprocess==0.7.0
#       - pure-eval==0.2.3
#       - pygments==2.19.2
#       - pyzmq==27.0.0
#       - seaborn==0.13.2
#       - stack-data==0.6.3
#       - statsmodels==0.14.5
#       - traitlets==5.14.3
#       - typing-extensions==4.14.1
#       - wcwidth==0.2.13
#       - zope-interface==7.2
# prefix: /home/sd96/miniconda/envs/wastewater
